### ISSUE TITLE
Não aparece o radar para a Policia (VRPEX)

### ISSUE THREAD

**Issue by jooaootavio** [kvalue/emp_lc#1]
Testei, não consegui fazer o radar funcionar para a polícia. Ao iniciar o roubo do carro, a mensagem chega para a polícia, porém não aparece o carro no mapa para rastrear.

Outra coisa, é possível inserir uma regra que o roubo só poderá ocorrer se tiver X policiais em serviço?

**Comment by kvalue** [comment]
O problema do radar parece que arrumei.

Opçao de só iniciar com x numero de policiais foi adicionado
