### ISSUE TITLE
Radar não funciona para Polícia

### ISSUE THREAD

**Issue by jooaootavio** [kvalue/emp_lc#2]
Olá Lc, primeiramente parabenizar pelo Script! Muito  bom.

Fiz os testes, mais tudo funciona perfeitinho como deve funcionar, somente o carro que não aparece no radar da Polícia.

tem algo que posso fazer para ajudar?

**Comment by kvalue** [comment]
Agradeço, que bom que gostou!

Então, tá ocorrendo uns problemas por conta da migração de veiculos, mas que pelos meus testes só ocorre quando a pessoa sai do carro roubado, ainda nao consegui reproduzir esse bug de nao aparecer o radar pra ninguem
